<a href="https://colab.research.google.com/github/BHARATH-D-095/Task-s-/blob/main/ASSIGNMENT_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                                       ######   ASSIGNMENT 1  ######
## Program for multiplying two matrices

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
## method 1: solving by using a given values of elements in two 3x3 matrices

mat1=[[1,2,3],[4,5,6],[7,8,9]]
mat2=[[1,1,1,],[2,2,2],[3,3,3]]
m1=np.array(mat1)
m2=np.array(mat2)
result=[[0,0,0],[0,0,0],[0,0,0]]
result=m1*m2              ### results a multiplicated value matrix with respective positioned elements product of mat1 and mat2
r=np.array(result)
r

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])

In [ ]:
r1=np.dot(mat1,mat2)    ### results in product of mat1 and mat2 using 'dot' command
r1

array([[14, 14, 14],
       [32, 32, 32],
       [50, 50, 50]])

In [ ]:
## method 2: solving using iterative statement for given vlaues of elemnets in two 3x3 matrices

mat1=[[1,2,3],[4,5,6],[7,8,9]]
mat2=[[1,1,1,],[2,2,2],[3,3,3]]
res=[[0,0,0],
     [0,0,0],
     [0,0,0]]
for i in range(len(mat1)):
    for j in range(len(mat2)):
        for k in range(len(mat2)):             ### both given matrices are 2-D and of same order in columns and rows
            res[i][j]+=mat1[i][k]*mat2[k][j]        ### hence product of matrices can be done
r=np.array(res)
r

array([[14, 14, 14],
       [32, 32, 32],
       [50, 50, 50]])

In [ ]:
    
    print('Program for multiplication of two matrices by accepting matrix elements at runtime\n')
    print('PRESS *ENTER* AFTER EVERY ENTRY\n')
    print('Enter no.of rows and coulmns of matrix m1:')
    r1=int(input('no.of rows r1:'))
    c1=int(input('no.of columns c1:'))
    x1=r1*c1
    print('Matrix m1 is',r1,'x',c1,'ordered and can hold',x1,'elements')
    print('\nEnter no.of rows and coulmns of matrix m2:')
    r2=int(input('no.of rows r2:'))
    c2=int(input('no.of columns c2:'))
    x2=r2*c2
    print('Matrix m2 is',r2,'x',c2,'ordered and can hold',x2,'elements')
    
    if c1==r2:
        print('\nm1 and m2 matrix multiplication is possible')
        print('\nEnter',x1,'elements of m1 matrix with spaces: ')
        l1=input()
        elements1=l1.split()
        for i in range(len(elements1)):
            elements1[i]=int(elements1[i])
            m1=np.asarray(elements1)
            shape=(r1,c1)
            m1=m1.reshape(shape)
        print('\nm1 matrix is:\n',m1)
        print('\nEnter',x2,'elements of m2 matrix with spaces: ')
        l2=input()
        elements2=l2.split()
        for i in range(len(elements2)):
            elements2[i]=int(elements2[i])
            m2=np.asarray(elements2)
            shape=(r2,c2)
            m2=m2.reshape(shape)
        print('\nm2 amtrix is:\n',m2)
        print('\nProduct of m1 and m2 matrices is:')
        result=np.dot(m1,m2)
        print(result)
        print('Shape of resultant matrix is:',result.shape)
    else:
        print('\nm1 and m2 matrix multiplication is not possible as c1 and r2 are not equal.')

Program for multiplication of two matrices by accepting matrix elements at runtime

PRESS *ENTER* AFTER EVERY ENTRY

Enter no.of rows and coulmns of matrix m1:
no.of rows r1:2
no.of columns c1:2
Matrix m1 is 2 x 2 ordered and can hold 4 elements

Enter no.of rows and coulmns of matrix m2:
no.of rows r2:2
no.of columns c2:2
Matrix m2 is 2 x 2 ordered and can hold 4 elements

m1 and m2 matrix multiplication is possible

Enter 4 elements of m1 matrix with spaces: 
1 2 3 4

m1 matrix is:
 [[1 2]
 [3 4]]

Enter 4 elements of m2 matrix with spaces: 
2 3 4 5

m2 amtrix is:
 [[2 3]
 [4 5]]

Product of m1 and m2 matrices is:
[[10 13]
 [22 29]]
Shape of resultant matrix is: (2, 2)
